name: build-and-sync-osf

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup Pandoc (for Quarto compatibility)
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev

      - name: Install R packages
        run: Rscript scripts/setup_packages.R

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto
        run: quarto render reports/quarto/dmcel_overview.qmd

      - name: OSF Sync
        env:
          OSF_TOKEN: ${{ secrets.OSF_TOKEN }}
          OSF_PROJECT: ${{ secrets.OSF_PROJECT }}
          OSF_DATA_COMPONENT: ${{ secrets.OSF_DATA_COMPONENT }}
          OSF_REPORTS_COMPONENT: ${{ secrets.OSF_REPORTS_COMPONENT }}
        run: Rscript scripts/osf_sync.R